version: '3'
services: 
  db_postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_guru
       
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 9490:5432
