# config/database.yml
default: &default                                                                    
  adapter: postgresql                                                                
  encoding: unicode                                                                  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 9490
  username: postgres
  password: 123

development:
  <<: *default
  adapter: postgresql
  database: test_guru

test:
  <<: *default                                                                       
  database: test-guru_test

production:
  <<: *default                                                                       
  database: test-guru_production
